### ISSUE TITLE
你好，请问多个module 在main里面怎么使用？

### ISSUE THREAD

**Issue by iChenlife** [qlwz/esp_framework#3]
module = new Relay();
module = new Ble();

这样出错，
抱歉，半路出家的，学艺不精，搜索了指向类指针的使用，还是不会

**Comment by qlwz** [comment]
module->next = new Ble();

**Comment by iChenlife** [comment]
刚搞定了，
    module = new Relay();
    module->next =  new Relay();
上面是2个module，请问可以增加无数个吗？
